---
- hosts: windows
  gather_facts: False
  tasks:
  - name: Update registry path 
    ansible.windows.win_regedit:
      path: HKLM:\SYSTEM\CurrentControlSet\Services\Lanmanserver\Parameters
      name: Hidden
      data: 0
      type: dword
