---
- hosts: windows
  gather_facts: False
  tasks:
  - name: Update registry path 
    ansible.windows.win_regedit:
      path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer
      name: NoDriveTypeAutoRun
      data: FF
      type: dword
