---
- hosts: windows
  gather_facts: False
  tasks:
  - name: Update registry path 
    ansible.windows.win_regedit:
      path: HKLM:\Software\Microsoft\Windows NT\CurrentVersion\Setup\RecoveryConsole\
      name: SecurityLevel
      data: 0
      type: dword
